### ISSUE TITLE
r.in.kinect make error: recipe for target 'OBJ.x86_64-pc-linux-gnu/main.o' failed

### ISSUE THREAD

**Issue by acritarchy** [petrasovaa/r.in.kinect#5]
Hello~

Attempting to compile r.in.kinect for Grass 7.8.3, Ubuntu 18.04, PCL 1.11, following instructions given in Readme.md. Have been working on getting this running for some time now; any insight will be greatly appreciated!

Input: ~/tangiblelandscape/r.in.kinect$ sudo make MODULE_TOPDIR=/usr/lib/grass78

Final error: 

/usr/lib/grass78/include/Make/Compile.make:35: recipe for target 'OBJ.x86_64-pc-linux-gnu/main.o' failed
make: *** [OBJ.x86_64-pc-linux-gnu/main.o] Error 1

Complete output:

~/tangiblelandscape/r.in.kinect$ make MODULE_TOPDIR=/usr/lib/grass78
c++ -Wdate-time -D_FORTIFY_SOURCE=2 -g -O2 -fdebug-prefix-map=/build/grass-HsqAiw/grass-7.8.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security  -I/usr/lib/grass78/include -I/usr/lib/grass78/include   -std=c++14 -march=native  -Wno-deprecated -O0 -I/usr/include/gdal -I/usr/include -fopenmp -DPACKAGE=\""grassmods"\"  -I/usr/include/postgresql -I/usr/local/include/pcl-1.11 -I/usr/include/eigen3 -I/usr/lib/grass78/include -I/usr/lib/grass78/include -DRELDIR=\"/home/emlab/tangiblelandscape/r.in.kinect\" -o OBJ.x86_64-pc-linux-gnu/main.o -c main.cpp
In file included from /usr/include/gdal/cpl_port.h:66:0,
                 from /usr/include/gdal/cpl_progress.h:33,
                 from /usr/include/gdal/ogr_api.h:43,
                 from /usr/lib/grass78/include/grass/vect/dig_structs.h:27,
                 from /usr/lib/grass78/include/grass/vect/digit.h:3,
                 from /usr/lib/grass78/include/grass/vector.h:4,
                 from binning.h:7,
                 from main.cpp:30:
/usr/include/gdal/cpl_config.h:163:0: warning: "HAVE_POSIX_MEMALIGN" redefined
 #define HAVE_POSIX_MEMALIGN 1
 
In file included from /usr/local/include/pcl-1.11/pcl/console/print.h:44:0,
                 from /usr/local/include/pcl-1.11/pcl/conversions.h:53,
                 from /usr/local/include/pcl-1.11/pcl/common/io.h:48,
                 from /usr/local/include/pcl-1.11/pcl/filters/filter.h:43,
                 from main.cpp:17:
/usr/local/include/pcl-1.11/pcl/pcl_config.h:40:0: note: this is the location of the previous definition
 #define HAVE_POSIX_MEMALIGN
 
main.cpp: In function ‘int main(int, char**)’:
main.cpp:811:28: error: no matching function for call to ‘calibrate(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&)’
             calibrate(cloud);
                            ^
In file included from main.cpp:32:0:
calibrate.h:19:6: note: candidate: template<class PointT> void calibrate(boost::shared_ptr<pcl::PointCloud<PointT> >&)
 void calibrate(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud) {
      ^~~~~~~~~
calibrate.h:19:6: note:   template argument deduction/substitution failed:
main.cpp:811:28: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
             calibrate(cloud);
                            ^
main.cpp:817:55: error: no matching function for call to ‘rotate_with_matrix(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, Eigen::Matrix4f&)’
             rotate_with_matrix(cloud, transform_matrix);
                                                       ^
In file included from main.cpp:32:0:
calibrate.h:113:13: note: candidate: template<class PointT> void rotate_with_matrix(boost::shared_ptr<pcl::PointCloud<PointT> >&, Eigen::Matrix4f)
 inline void rotate_with_matrix(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud,
             ^~~~~~~~~~~~~~~~~~
calibrate.h:113:13: note:   template argument deduction/substitution failed:
main.cpp:817:55: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
             rotate_with_matrix(cloud, transform_matrix);
                                                       ^
main.cpp:822:49: error: no matching function for call to ‘trim_Z(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, double&, double&)’
             trim_Z(cloud, zrange_min, zrange_max);
                                                 ^
main.cpp:298:13: note: candidate: template<class PointT> void trim_Z(boost::shared_ptr<pcl::PointCloud<PointT> >&, double, double)
 inline void trim_Z(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud,
             ^~~~~~
main.cpp:298:13: note:   template argument deduction/substitution failed:
main.cpp:822:49: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
             trim_Z(cloud, zrange_min, zrange_max);
                                                 ^
main.cpp:825:30: error: no matching function for call to ‘rotate_Z(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, double&)’
         rotate_Z(cloud, angle);
                              ^
main.cpp:287:13: note: candidate: template<class PointT> void rotate_Z(boost::shared_ptr<pcl::PointCloud<PointT> >&, double)
 inline void rotate_Z(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud, double angle) {
             ^~~~~~~~
main.cpp:287:13: note:   template argument deduction/substitution failed:
main.cpp:825:30: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
         rotate_Z(cloud, angle);
                              ^
main.cpp:829:59: error: no matching function for call to ‘clipNSEW(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, double&, double&, double&, double&)’
             clipNSEW(cloud, clip_N, clip_S, clip_E, clip_W);
                                                           ^
main.cpp:255:13: note: candidate: template<class PointT> void clipNSEW(boost::shared_ptr<pcl::PointCloud<PointT> >&, double, double, double, double)
 inline void clipNSEW(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud, double clip_N, double clip_S, double  clip_E, double clip_W) {
             ^~~~~~~~
main.cpp:255:13: note:   template argument deduction/substitution failed:
main.cpp:829:59: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
             clipNSEW(cloud, clip_N, clip_S, clip_E, clip_W);
                                                           ^
main.cpp:866:33: error: no matching function for call to ‘calibrate_bbox(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&)’
             calibrate_bbox(cloud);
                                 ^
In file included from main.cpp:32:0:
calibrate.h:75:6: note: candidate: template<class PointT> void calibrate_bbox(boost::shared_ptr<pcl::PointCloud<PointT> >&)
 void calibrate_bbox(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud) {
      ^~~~~~~~~~~~~~
calibrate.h:75:6: note:   template argument deduction/substitution failed:
main.cpp:866:33: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
             calibrate_bbox(cloud);
                                 ^
main.cpp:873:91: error: no matching function for call to ‘autotrim(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, double&, double&, double&, double&, double&)’
 utotrim(cloud, autoclip_N, autoclip_S, autoclip_E, autoclip_W, trim_tolerance);
                                                                              ^
main.cpp:348:6: note: candidate: template<class PointT> void autotrim(boost::shared_ptr<pcl::PointCloud<PointT> >&, double&, double&, double&, double&, double)
 void autotrim(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud, double &clip_N, double &clip_S, double &clip_E, double &clip_W, double tolerance) {
      ^~~~~~~~
main.cpp:348:6: note:   template argument deduction/substitution failed:
main.cpp:873:91: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
 utotrim(cloud, autoclip_N, autoclip_S, autoclip_E, autoclip_W, trim_tolerance);
                                                                              ^
main.cpp:875:79: error: no matching function for call to ‘trimNSEW(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, double&, double&, double&, double&)’
                trimNSEW(cloud, autoclip_N, autoclip_S, autoclip_E, autoclip_W);
                                                                              ^
main.cpp:270:13: note: candidate: template<class PointT> void trimNSEW(boost::shared_ptr<pcl::PointCloud<PointT> >&, double, double, double, double)
 inline void trimNSEW(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud, double trim_N, double trim_S, double  trim_E, double trim_W) {
             ^~~~~~~~
main.cpp:270:13: note:   template argument deduction/substitution failed:
main.cpp:875:79: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
                trimNSEW(cloud, autoclip_N, autoclip_S, autoclip_E, autoclip_W);
                                                                              ^
main.cpp:898:44: error: no matching function for call to ‘smooth(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, double&)’
                 smooth(cloud, smooth_radius);
                                            ^
main.cpp:309:13: note: candidate: template<class PointT> void smooth(boost::shared_ptr<pcl::PointCloud<PointT> >&, double)
 inline void smooth(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud, double radius) {
             ^~~~~~
main.cpp:309:13: note:   template argument deduction/substitution failed:
main.cpp:898:44: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
                 smooth(cloud, smooth_radius);
                                            ^
main.cpp:943:86: error: no matching function for call to ‘binning(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, char*&, bound_box*, double&, double&, double&, double, double&, char*&)’
                 scale, zexag, region3D ? -zrange_max : bbox.B, offset, method);
                                                                              ^
In file included from main.cpp:30:0:
binning.h:20:13: note: candidate: template<class PointT> void binning(boost::shared_ptr<pcl::PointCloud<PointT> >&, char*, bound_box*, double, double, double, double, double, const char*)
 inline void binning(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud,
             ^~~~~~~
binning.h:20:13: note:   template argument deduction/substitution failed:
main.cpp:943:86: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
                 scale, zexag, region3D ? -zrange_max : bbox.B, offset, method);
                                                                              ^
main.cpp:966:71: error: no matching function for call to ‘binning_color(pcl::PointCloud<pcl::PointXYZRGB>::Ptr&, char*&, bound_box*, double&)’
             binning_color(cloud, color_output, &bbox, color_resolution);
                                                                       ^
In file included from main.cpp:31:0:
binning_color.h:70:13: note: candidate: template<class PointT> void binning_color(boost::shared_ptr<pcl::PointCloud<PointT> >&, char*, bound_box*, double)
 inline void binning_color(boost::shared_ptr<pcl::PointCloud<PointT>> &cloud,
             ^~~~~~~~~~~~~
binning_color.h:70:13: note:   template argument deduction/substitution failed:
main.cpp:966:71: note:   ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr {aka std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >}’ is not derived from ‘boost::shared_ptr<pcl::PointCloud<PointT> >’
             binning_color(cloud, color_output, &bbox, color_resolution);
                                                                       ^
/usr/lib/grass78/include/Make/Compile.make:35: recipe for target 'OBJ.x86_64-pc-linux-gnu/main.o' failed
make: *** [OBJ.x86_64-pc-linux-gnu/main.o] Error 1

**Comment by petrasovaa** [comment]
I wonder if it's because PCL 1.11, I haven't tested it with it. Could you try 1.10?

**Comment by acritarchy** [comment]
That did it, thank you!
